# Generated by Django 6.0.2 on 2026-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair_care', 'Hair Care'), ('skin_care', 'Skin Care'), ('groom_services', 'Groom Services'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
