# Generated by Django 6.0.2 on 2026-02-09 17:47

from django.db import migrations, models


def migrate_groom_to_barber(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.filter(category='groom_services').update(category='barber_services')


def migrate_barber_to_groom(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.filter(category='barber_services').update(category='groom_services')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_price'),
    ]

    operations = [
        migrations.RunPython(migrate_groom_to_barber, migrate_barber_to_groom),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hair_care', 'Hair Care'), ('skin_care', 'Skin Care'), ('barber_services', 'Barber Services'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
