# Generated by Django 6.0.2 on 2026-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiontoggle',
            name='key',
            field=models.CharField(choices=[('edit_client_identity', 'Edit client identity fields'), ('export_campaigns', 'Export campaign lists')], max_length=64),
        ),
    ]
