# Generated by Django 6.0.2 on 2026-02-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=255)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField()),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groom_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_groom_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', 'groom_name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='groom_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.groomevent'),
        ),
        migrations.AddIndex(
            model_name='groomevent',
            index=models.Index(fields=['event_date'], name='appointment_event_d_1d7e54_idx'),
        ),
        migrations.AddIndex(
            model_name='groomevent',
            index=models.Index(fields=['groom_name'], name='appointment_groom_n_398627_idx'),
        ),
    ]
