# Generated by Django 6.0.2 on 2026-02-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_groomevent_appointment_groom_event_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='groomevent',
            name='appointment_event_d_1d7e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='groomevent',
            name='appointment_groom_n_398627_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='groom_event',
        ),
        migrations.DeleteModel(
            name='GroomEvent',
        ),
    ]
