# Generated by Django 6.0.2 on 2026-02-09 17:55

from decimal import Decimal

from django.db import migrations, models


def seed_appointment_services_and_total_price(apps, schema_editor):
    Appointment = apps.get_model('appointments', 'Appointment')
    Service = apps.get_model('services', 'Service')
    service_prices = dict(Service.objects.values_list('id', 'price'))

    for appointment in Appointment.objects.exclude(service_id__isnull=True).iterator():
        appointment.services.add(appointment.service_id)
        appointment.total_price = service_prices.get(appointment.service_id) or Decimal("0")
        appointment.save(update_fields=['total_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_groomevent_appointment_event_d_1d7e54_idx_and_more'),
        ('services', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='appointments_multi', to='services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(seed_appointment_services_and_total_price, migrations.RunPython.noop),
    ]
