# Generated by Django 6.0.2 on 2026-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundsession',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='ai-playground/session-selfies/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='playgroundsession',
            name='selfie_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
