# Generated by Django 6.0.2 on 2026-02-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0002_playgroundsession_selfie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundsession',
            name='last_generation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlaygroundRateLimitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start Session'), ('generate', 'Generate Preview')], max_length=24)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_limit_events', to='ai_playground.playgroundsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'ip_address', 'created_at'], name='ai_playgrou_action_8bcaa6_idx')],
            },
        ),
    ]
