# Generated by Django 6.0.2 on 2026-02-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0003_playgroundsession_last_generation_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgroundstyle',
            name='prompt_hint',
        ),
    ]
