# Generated by Django 6.0.2 on 2026-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0005_alter_playgroundstyle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundgeneration',
            name='custom_style_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
