# Generated by Django 6.0.2 on 2026-02-10 13:08

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_COLOR_OPTIONS = [
    ("Natural Black", "#1B1B1B", "both", 10),
    ("Soft Black", "#2A2521", "both", 20),
    ("Dark Brown", "#3E2D22", "both", 30),
    ("Chocolate Brown", "#5A3A28", "both", 40),
    ("Light Brown", "#816048", "both", 50),
    ("Ash Brown", "#615C56", "both", 60),
    ("Golden Blonde", "#D4B06B", "both", 70),
    ("Copper", "#B86936", "both", 80),
    ("Auburn", "#7E3026", "both", 90),
    ("Silver Gray", "#A5A9B0", "both", 100),
]


def seed_default_color_options(apps, schema_editor):
    ColorOption = apps.get_model("ai_playground", "PlaygroundColorOption")
    for name, hex_code, scope, sort_order in DEFAULT_COLOR_OPTIONS:
        ColorOption.objects.update_or_create(
            name=name,
            scope=scope,
            defaults={
                "hex_code": hex_code,
                "is_active": True,
                "sort_order": sort_order,
            },
        )


def unseed_default_color_options(apps, schema_editor):
    ColorOption = apps.get_model("ai_playground", "PlaygroundColorOption")
    names = [name for name, _, _, _ in DEFAULT_COLOR_OPTIONS]
    ColorOption.objects.filter(name__in=names, scope="both").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0006_playgroundgeneration_custom_style_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundBeardStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(upload_to='ai-playground/beard-styles/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlaygroundColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hex_code', models.CharField(default='#111111', max_length=7)),
                ('scope', models.CharField(choices=[('hair', 'Hair'), ('beard', 'Beard'), ('both', 'Hair + Beard')], default='both', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='playgroundgeneration',
            name='beard_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='ai_playground.playgroundbeardstyle'),
        ),
        migrations.AddField(
            model_name='playgroundgeneration',
            name='beard_color_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beard_generations', to='ai_playground.playgroundcoloroption'),
        ),
        migrations.AddField(
            model_name='playgroundgeneration',
            name='hair_color_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hair_generations', to='ai_playground.playgroundcoloroption'),
        ),
        migrations.RunPython(seed_default_color_options, unseed_default_color_options),
    ]
