# Generated by Django 6.0.2 on 2026-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_playground', '0007_playgroundbeardstyle_playgroundcoloroption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundstyle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
